sudo: false
language: node_js
cache:
  directories:
  - node_modules
after_script:
- npm run codecov
stages:
  - lint
  - test
#  - test:frontend
  - coverage
jobs:
  fast_finish: true
  allow_failures:
    - script: npm run test:frontend
  include:
    - stage: lint
      node_js: 12
      script: npm run lint
    - stage: test
      node_js: 13
      script:
        - npm run test
    - stage: test
      node_js: 12
      script: 
        - npm run test
        - npm run test:frontend:hooks
    - stage: test
      node_js: node
      script: 
        - npm run test
# TODO: switch this to webdriver.io and turn on in CI
#    - stage: test:frontend
#      node_js: node
#      script: npm run test:frontend
    - stage: coverage
      node_js: 12
      script: npm run coverage
