sudo: false
language: node_js
cache:
  directories:
  - node_modules
after_script:
- npm run codecov
stages:
  - lint
  - test
jobs:
  fast_finish: true
  allow_failures:
    - script: npm run test:frontend
  include:
    - stage: lint
      node_js: 12
      script: npm run lint
    - stage: test
      node_js: 13
      script:
        - npm run test
    - stage: test
      node_js: 12
      script:
        - npm run test
    - stage: test
      node_js: 14
      script:
        - npm run coverage
